version: "3"

services:
  core-application:
    image: micro-frontends/examples/run-time/iframes/core-application
    container_name: iframe-core-application
    build:
      context: .
      dockerfile: config/core-application/Dockerfile
    ports:
      - "3000:3000"
    restart: always
  child-application:
    image: micro-frontends/examples/run-time/iframes/child-application
    container_name: iframe-child-application
    build:
      context: .
      dockerfile: config/child-application/Dockerfile
    ports:
      - "3001:3000"
    restart: always